apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml --volumes hostPath
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auditoria
  name: auditoria
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auditoria
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml --volumes hostPath
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/auditoria-default: "true"
        io.kompose.service: auditoria
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - env:
            - name: APP_ENV
              value: local
            - name: CONTAINER_ROLE
              value: app
          image: rats4final/auditoria5
          stdin: true
          tty: true
          name: auditoria
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
status: {}
