version: "3.9"
services:
    #auditoria app
    auditoria:
        build:
            context: .
            target: auditoria
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - node_modules:/var/www/node_modules
        ports:
            - "8000:8000"
        depends_on:
          db:
            condition: service_healthy


    #MySQL database
    db:
        image: mysql:latest
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USERNAME=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

volumes:
    db-data: ~
    node_modules: ~
